name: ASP.NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore WMS.Tests
      run: dotnet restore WMS.Tests/WMS.Tests.csproj

    - name: Build WMS.Tests
      run: dotnet build WMS.Tests/WMS.Tests.csproj --configuration Release --no-restore

    - name: Run NUnit Tests
      run: dotnet test WMS.Tests/WMS.Tests.csproj --configuration Release --no-build --logger trx

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: TestResults
        path: '**/*.trx'
